#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

if [ -z "$2" ];
then
	for sub_dom in "www" "lb-01" "web-01" "web-02"
	do
		get_record "$1" "$sub_dom"
	done
else
	get_record "$1" "$2"
fi
