#!/usr/bin/env bash
# install and configure HAproxy on your lb-01 server

sudo apt-get update -y
sudo apt -get install haproxy -y

echo "
frontend jackyarrey
	bind *:80
	default_backend arreyjacky

backend arreyjacky
	balance roundrobin
	server 119939-web-01 100.26.161.221:80 check
	server 119939-web-02 18.207.112.95:80 check
" > /etc/haproxy/haproxy.cfg
sudo sed -i 's/ENABLED=0/ENABLED=1' /etc/default/aproxy

sudo service aproxy restart
