#!/usr/bin/env bash
# Install and configure HAProxy on yyour lb-01 server

sudo apt-get update -y
sudo apt-get install haproxy -y

# Configure the server to both frontend and backend
echo "
frontend jacksonarrey_frontend
    bind *:80
    mode http
    default_backend jacksonarrey_backend

backend jacksonarrey_backend
    balance roundrobin
    server 119939-web-01 100.26.161.221:80 check
    server 119939-web-02 18.207.112.95:80 check
">> /etc/haproxy/haproxy.cfg

# Enabling HAproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

# Restart HAproxy
sudo service haproxy restart
