#!/usr/bin/env bash
# Install ufw firewall and block all incoming traffic except
# ports 22, 80 and 443

# install ufw, support both IPv4 and IPv6, and ensure default values
sudo apt-get -y install ufw
sudo sed -i "s/IPV6=no/IPV6=yes/" /etc/default/ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming

# allow only traffic from select ports
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# enable ufw
sudo ufw enable
